# Generated by Django 5.2 on 2025-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('time_period', models.CharField(max_length=25)),
                ('summary', models.CharField(max_length=120)),
            ],
        ),
    ]
