# Generated by Django 5.2 on 2025-04-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='FunFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factImage', models.ImageField(blank=True, upload_to='')),
                ('factText', models.TextField(blank=True)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
